### ISSUE TITLE
Nacos的元数据配置不上去

### ISSUE THREAD

**Issue by zdq7418** [polarismesh/polaris-java-agent#102]
polaris-java-agent版本：1.4.0-beta
Spring Boot 版本：2.1.4.RELEASE
nacos.client 版本：1.3.2
nacos服务端版本： 2.1.2
项目配置文件：
```
spring:
  application:
    name: 
  cloud:
    inetutils:
      preferred-networks: ${preferred-networks:}
    nacos:
      config:
        server-addr: ${nacos-addr:}
        namespace: ${nacos-namespace:}
        file-extension: yml
        # nacos配置对应的信息
        ext-config:
      discovery:
        server-addr: ${nacos-addr:}
        namespace: ${nacos-namespace:}
        metadata:
          version: 1.0.1
```
polaris-java-agent配置文件：
```
spring.application.name=
spring.cloud.discovery.enabled=true
spring.cloud.polaris.address=grpc://127.0.0.1:8091
spring.cloud.polaris.namespace=polarismesh
spring.cloud.polaris.enabled=true
spring.cloud.polaris.discovery.enabled=true
spring.cloud.polaris.discovery.registerEnabled=true
spring.cloud.polaris.stat.enabled=true
spring.cloud.polaris.stat.port=0
spring.cloud.tencent.rpc-enhancement.reporter.enabled=true
spring.cloud.nacos.enabled=true
spring.cloud.nacos.username=
spring.cloud.nacos.password=
spring.cloud.nacos.discovery.enabled=true
spring.cloud.nacos.discovery.register=false
spring.cloud.nacos.discovery.server-addr=
```
启动完成之后，北极星和nacos后台都能看到服务，但是nacos的元信息里没有我配置的版本数据并且自动加上了内网地址的元信息数据，去除polaris-java-agent，nacos里能看到我配置的元信息的版本数据，可能是代理没有读到我配置的元数据信息，或者覆盖掉了
